FROM ghcr.io/squarefactory/xcat-rocky:0.1.3-xcat2.16.3-rocky8.4 as build

FROM scratch

COPY --from=build / /

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

COPY xcat-init.bash /xcat-init.bash
RUN chmod 700 /xcat-init.bash
COPY xcat-init.service /etc/systemd/system/xcat-init.service
RUN systemctl enable xcat-init

ENTRYPOINT ["/sbin/init"]

STOPSIGNAL SIGRTMIN+3
